version: '2.4'

services:
  db:
    image: mysql:8.0.22
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: 'avito'
      MYSQL_USER: 'john'
      MYSQL_PASSWORD: 'Test12345%'
      MYSQL_ROOT_PASSWORD: 'testroot'
    ports:
      - "3306:3306"
    network_mode: "host"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      timeout: 20s
      retries: 10
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web_api
    restart: always
    ports: 
      - "8000:8000"
    depends_on: 
      db:
        condition: "service_healthy"
    network_mode: "host"
    